#!/usr/bin/env node

import { existsSync, lstatSync, mkdtempSync, readFileSync, readdirSync, readlinkSync, statSync } from "node:fs";
import { createHash } from "node:crypto";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const skillRoot = path.resolve(
  scriptDir,
  "../../skills/growth/seo-growth-workspace",
);
const args = process.argv.slice(2);

function usage() {
  return `Usage:
  node dev/seo-growth-workspace/evaluate-release.mjs [--json] [--validator-report <path>] [--profile-root name=/path/to/repo]

Scores the portable seo-growth-workspace release candidate and optionally inspects
real repo profiles without modifying them. Higher score is better.

Blocking gates: by default the evaluator executes validate-skill.mjs once with a
report path and consumes its machine-readable report; pass requires both the
validator and its command-inventory subgate green. --validator-report consumes an
existing report instead (rejected when missing, stale, wrong-digest, duplicate,
or malformed).`;
}

function argValues(name) {
  return args.flatMap((arg, index) => (arg === name ? [args[index + 1]] : []));
}

function walk(root, files = []) {
  for (const entry of readdirSync(root)) {
    const absolute = path.join(root, entry);
    const relative = path.relative(skillRoot, absolute);
    if (entry === ".git" || entry === "node_modules") continue;
    if (statSync(absolute).isDirectory()) {
      walk(absolute, files);
      continue;
    }
    files.push(relative);
  }
  return files;
}

function walkRelative(root, relativeRoot = "") {
  if (!existsSync(root)) return [];
  return readdirSync(root).flatMap((entry) => {
    const absolute = path.join(root, entry);
    const relative = path.join(relativeRoot, entry);
    if (statSync(absolute).isDirectory()) return walkRelative(absolute, relative);
    return [relative];
  });
}

function read(relativePath) {
  return readFileSync(path.join(skillRoot, relativePath), "utf-8");
}

function exists(relativePath) {
  return existsSync(path.join(skillRoot, relativePath));
}

const VALIDATOR_REPORT_VERSION = 1;
const VALIDATOR_REPORT_MAX_AGE_MS = 15 * 60 * 1000;
const VALIDATOR_REPORT_MAX_FUTURE_SKEW_MS = 2 * 60 * 1000;

function hash(value) {
  return createHash("sha256").update(String(value)).digest("hex");
}

// Byte-for-byte the same digest validate-skill.mjs stamps into its report:
// both sides must agree on what "the current skill source" hashes to.
function treeDigest(root) {
  const visit = (dir, relative = "") => readdirSync(dir).sort().flatMap((entry) => {
    const absolute = path.join(dir, entry);
    const next = path.join(relative, entry);
    const stats = lstatSync(absolute);
    if (stats.isSymbolicLink()) return [`${next}:link:${readlinkSync(absolute)}`];
    if (stats.isDirectory()) return [`${next}:dir`, ...visit(absolute, next)];
    return [`${next}:file:${hash(readFileSync(absolute))}`];
  });
  return hash(visit(root).join("\n"));
}

// Binds a report to the validator implementation whose results it attests, not
// just to the skill tree: a report generated by an older validator/inventory
// implementation must not green-light the current gates.
function devToolingDigest() {
  return hash(
    ["validate-skill.mjs", "command-inventory.mjs"]
      .map((file) => hash(readFileSync(path.join(scriptDir, file), "utf-8")))
      .join("\n"),
  );
}

// The canonical section inventory is derived from the validator's own source, so
// a report cannot green-light the gates without attesting every section the
// current validator actually runs (a hand-edited or truncated report is rejected),
// and validator changes never drift from a hand-maintained list here.
function validatorSectionInventory(validatorScript) {
  return [...readFileSync(validatorScript, "utf-8").matchAll(/^section\(\s*"([^"]+)"/gm)].map((match) => match[1]);
}

function runBlockingGates() {
  const explicitReport = argValues("--validator-report")[0] ?? null;
  const validatorScript = path.join(scriptDir, "validate-skill.mjs");
  const reportPath =
    explicitReport ??
    path.join(mkdtempSync(path.join(tmpdir(), "seo-release-eval-")), "validator-report.json");
  let validatorExit = null;
  if (!explicitReport) {
    const validatorRun = spawnSync(process.execPath, [validatorScript, "--report", reportPath], {
      encoding: "utf-8",
    });
    validatorExit = validatorRun.error ? null : validatorRun.status;
  }

  const rejections = [];
  let report = null;
  if (!existsSync(reportPath)) {
    rejections.push(`missing validator report at ${reportPath}`);
  } else {
    try {
      report = JSON.parse(readFileSync(reportPath, "utf-8"));
    } catch (error) {
      rejections.push(`malformed validator report: ${error.message}`);
    }
  }
  if (report) {
    if (report.reportVersion !== VALIDATOR_REPORT_VERSION) {
      rejections.push(`malformed validator report: unsupported reportVersion ${JSON.stringify(report.reportVersion)}`);
      report = null;
    } else if (
      !Array.isArray(report.sections) ||
      !report.sections.every(
        (entry) => entry && typeof entry === "object" && typeof entry.name === "string" && typeof entry.result === "string",
      ) ||
      typeof report.pass !== "boolean" ||
      typeof report.generatedAt !== "string" ||
      typeof report.sourceDigest !== "string" ||
      typeof report.toolingDigest !== "string" ||
      typeof report.commandInventory?.result !== "string" ||
      !(Number.isInteger(report.commandInventory.exit) || report.commandInventory.exit === null)
    ) {
      rejections.push("malformed validator report: missing or malformed required fields");
      report = null;
    }
  }
  let failedSections = [];
  if (report) {
    const generated = Date.parse(report.generatedAt);
    if (!Number.isFinite(generated)) {
      rejections.push(`malformed validator report: unparseable generatedAt ${JSON.stringify(report.generatedAt)}`);
    } else {
      const age = Date.now() - generated;
      if (age > VALIDATOR_REPORT_MAX_AGE_MS || age < -VALIDATOR_REPORT_MAX_FUTURE_SKEW_MS) {
        rejections.push(`stale validator report: generatedAt ${report.generatedAt} is outside the accepted window`);
      }
    }
    const sectionNames = report.sections.map((entry) => entry.name);
    if (new Set(sectionNames).size !== sectionNames.length) {
      rejections.push("duplicate section entries in validator report");
    }
    const expectedSections = validatorSectionInventory(validatorScript);
    const reportedSections = new Set(sectionNames);
    const missingSections = expectedSections.filter((name) => !reportedSections.has(name));
    const unknownSections = sectionNames.filter((name) => !expectedSections.includes(name));
    if (missingSections.length > 0 || unknownSections.length > 0) {
      rejections.push(`incomplete validator report: section inventory mismatch (missing: ${missingSections.join(", ") || "none"}; unknown: ${unknownSections.join(", ") || "none"})`);
    }
    const inventorySection = report.sections.find((entry) => entry.name === "command inventory and foreign-CWD matrix");
    if (inventorySection && report.commandInventory.result !== inventorySection.result) {
      rejections.push(`malformed validator report: commandInventory.result ${report.commandInventory.result} disagrees with its section result ${inventorySection.result}`);
    }
    if (report.commandInventory.result === "PASS" && report.commandInventory.exit !== 0) {
      rejections.push(`malformed validator report: commandInventory result PASS with exit ${report.commandInventory.exit}`);
    }
    const expectedDigest = treeDigest(skillRoot);
    if (report.sourceDigest !== expectedDigest) {
      rejections.push(`wrong-digest validator report: report attests ${report.sourceDigest}, current skill source digest is ${expectedDigest}`);
    }
    const expectedToolingDigest = devToolingDigest();
    if (report.toolingDigest !== expectedToolingDigest) {
      rejections.push(`wrong-digest validator report: report attests tooling ${report.toolingDigest}, current validator/inventory implementation digest is ${expectedToolingDigest}`);
    }
    failedSections = report.sections.filter((entry) => entry.result !== "PASS").map((entry) => entry.name);
    if (report.pass && failedSections.length > 0) {
      rejections.push(`malformed validator report: pass is true but sections failed (${failedSections.join(", ")})`);
    }
    if (!explicitReport && validatorExit !== (report.pass ? 0 : 1)) {
      rejections.push(`malformed validator report: validator exit ${validatorExit} disagrees with report pass ${report.pass}`);
    }
  }

  const gates = [];
  if (report && rejections.length === 0) {
    gates.push({
      gate: "validate-skill",
      command: "node dev/seo-growth-workspace/validate-skill.mjs",
      exit: validatorExit ?? (report.pass ? 0 : 1),
      result: report.pass ? "PASS" : "FAIL",
      failedSections,
    });
    gates.push({
      gate: "command-inventory",
      command: report.commandInventory.command,
      exit: report.commandInventory.exit,
      result: report.commandInventory.result === "PASS" ? "PASS" : "FAIL",
    });
  }

  return {
    reportPath,
    selfExecuted: !explicitReport,
    rejections,
    gates,
    report,
    pass: rejections.length === 0 && gates.length === 2 && gates.every((gate) => gate.result === "PASS"),
  };
}

// --- Canonical gate-results artifact (deliverable of the slice-7 release) ---
//
// One versioned JSON holds EVERY release scenario row. Deterministic (a)-rows are
// imported from the validator's --report output and bound to it by digest; manual
// (b)-rows carry the same fields plus the source path-digest each attests. The
// Markdown release log is a *rendering* of this file, never an alternate source of
// truth. This evaluator self-executes the validator (runBlockingGates), imports the
// report's section rows, reads the manual rows, and REJECTS a missing, stale,
// wrong-digest, duplicate, malformed, or non-PASS-required artifact.
//
// reportVersion coupling: the artifact restates the validator's reportVersion. If the
// validator report schema changes, bump VALIDATOR_REPORT_VERSION (already shared with
// runBlockingGates) AND the validator's "gate-results artifact consumption rehearsal"
// section together — the artifact is rejected when its boundReportVersion drifts.
const GATE_RESULTS_VERSION = 1;
const GATE_RESULTS_FILENAME = "gate-results-4.0.0.json";

// The 17 enumerated manual (b)-gates from release-checklist.md § Enumerated v4
// scenario gates. Every one must be present exactly once and PASS; blocked/partial
// or a missing row fails the release.
const REQUIRED_MANUAL_GATES = [
  "b01-gbp-not-visible-gated-mutation",
  "b02-geo-grid-comparability",
  "b03-content-engine-native-revision-evidence",
  "b04-no-engine-fallback-evidence",
  "b05-unsupported-citation-fails",
  "b06-missing-information-gain-fails",
  "b07-local-personalized-ai-observation",
  "b08-predicted-ai-lift-fails",
  "b09-sparse-discovery-journey",
  "b10-community-source-pilot",
  "b11-token-swapped-community-pages-fail",
  "b12-affiliate-expiry-regulated-escalation",
  "b13-unauthorized-expired-code-fails",
  "b14-hidden-commission-fails",
  "b15-commerce-truth-lifecycle",
  "b16-rights-gated-authority-walk",
  "b17-authority-rental-opaque-indexer-fails",
];

function gateResultsPath() {
  return argValues("--gate-results")[0] ?? path.join(scriptDir, GATE_RESULTS_FILENAME);
}

// Consumes the canonical gate-results artifact against the fresh validator report
// (report) already produced by runBlockingGates. Returns rejection reasons; an empty
// list means the artifact is fresh, digest-bound, complete, and all required rows PASS.
function consumeGateResults(report) {
  const artifactPath = gateResultsPath();
  const rejections = [];
  const summary = { path: artifactPath, deterministicRows: 0, manualRows: 0, manualPass: 0, manualFail: 0 };

  if (!existsSync(artifactPath)) {
    rejections.push(`missing gate-results artifact at ${artifactPath}`);
    return { ...summary, rejections, pass: false };
  }

  let artifact = null;
  try {
    artifact = JSON.parse(readFileSync(artifactPath, "utf-8"));
  } catch (error) {
    rejections.push(`malformed gate-results artifact: ${error.message}`);
    return { ...summary, rejections, pass: false };
  }

  if (!artifact || typeof artifact !== "object" || Array.isArray(artifact)) {
    rejections.push("malformed gate-results artifact: not a JSON object");
    return { ...summary, rejections, pass: false };
  }
  if (artifact.gateResultsVersion !== GATE_RESULTS_VERSION) {
    rejections.push(`malformed gate-results artifact: unsupported gateResultsVersion ${JSON.stringify(artifact.gateResultsVersion)}`);
  }
  if (artifact.boundReportVersion !== VALIDATOR_REPORT_VERSION) {
    rejections.push(`malformed gate-results artifact: boundReportVersion ${JSON.stringify(artifact.boundReportVersion)} does not match validator reportVersion ${VALIDATOR_REPORT_VERSION}`);
  }
  const shippedVersion = read("SKILL.md").match(/^version:\s*(\S+)/m)?.[1];
  if (shippedVersion && artifact.skillVersion !== shippedVersion) {
    rejections.push(`stale gate-results artifact: skillVersion ${JSON.stringify(artifact.skillVersion)} does not match shipped SKILL.md version ${shippedVersion}`);
  }
  const deterministic = artifact.deterministic;
  const manual = artifact.manual;
  if (!deterministic || !Array.isArray(deterministic.rows) || !Array.isArray(manual)) {
    rejections.push("malformed gate-results artifact: missing deterministic.rows or manual array");
    return { ...summary, rejections, pass: false };
  }

  const expectedDigest = treeDigest(skillRoot);
  const expectedToolingDigest = devToolingDigest();
  if (artifact.sourceDigest !== expectedDigest) {
    rejections.push(`stale gate-results artifact: attests source ${artifact.sourceDigest}, current skill source digest is ${expectedDigest}`);
  }
  if (artifact.toolingDigest !== expectedToolingDigest) {
    rejections.push(`wrong-digest gate-results artifact: attests tooling ${artifact.toolingDigest}, current validator/inventory implementation digest is ${expectedToolingDigest}`);
  }

  // Deterministic (a)-rows: imported from the validator report and bound to it. The
  // artifact must reproduce the report's section inventory exactly — every section
  // once, no unknown/extra rows — with matching results and the attested digest.
  summary.deterministicRows = deterministic.rows.length;
  if (report && Array.isArray(report.sections)) {
    const reportResults = new Map(report.sections.map((entry) => [entry.name, entry.result]));
    const seen = new Set();
    for (const row of deterministic.rows) {
      if (!row || typeof row !== "object" || typeof row.scenario !== "string" || typeof row.result !== "string") {
        rejections.push("malformed gate-results artifact: malformed deterministic row");
        continue;
      }
      if (seen.has(row.scenario)) {
        rejections.push(`duplicate gate-results deterministic row: ${row.scenario}`);
        continue;
      }
      seen.add(row.scenario);
      if (!reportResults.has(row.scenario)) {
        rejections.push(`gate-results deterministic row not in validator report: ${row.scenario}`);
        continue;
      }
      if (row.result !== reportResults.get(row.scenario)) {
        rejections.push(`gate-results deterministic row ${row.scenario} attests ${row.result} but validator report says ${reportResults.get(row.scenario)}`);
      }
      if (row.result !== "PASS") {
        rejections.push(`non-PASS gate-results deterministic row: ${row.scenario} is ${row.result}`);
      }
      if (row.sourceDigest !== expectedDigest) {
        rejections.push(`stale gate-results deterministic row ${row.scenario}: attests ${row.sourceDigest}`);
      }
    }
    for (const name of reportResults.keys()) {
      if (!seen.has(name)) rejections.push(`gate-results deterministic rows omit validator section: ${name}`);
    }
  } else {
    rejections.push("cannot bind gate-results deterministic rows: no validator report available");
  }

  // Manual (b)-rows: the 17 enumerated non-waivable gates. Each must appear once,
  // carry the source digest it attests, and PASS. blocked/partial/FAIL blocks release.
  summary.manualRows = manual.length;
  const seenManual = new Set();
  for (const row of manual) {
    if (
      !row || typeof row !== "object" ||
      typeof row.id !== "string" ||
      typeof row.result !== "string" ||
      typeof row.evidence !== "string" ||
      typeof row.date !== "string" ||
      typeof row.operator !== "string"
    ) {
      rejections.push("malformed gate-results artifact: malformed manual row (needs id/result/evidence/date/operator)");
      continue;
    }
    if (seenManual.has(row.id)) {
      rejections.push(`duplicate gate-results manual row: ${row.id}`);
      continue;
    }
    seenManual.add(row.id);
    if (row.result === "PASS") summary.manualPass += 1;
    else summary.manualFail += 1;
    if (row.result !== "PASS") {
      rejections.push(`non-PASS gate-results manual row: ${row.id} is ${row.result} (blocked/partial/FAIL cannot satisfy a required gate)`);
    }
    if (row.sourceDigest !== expectedDigest) {
      rejections.push(`stale gate-results manual row ${row.id}: attests ${row.sourceDigest}, current skill source digest is ${expectedDigest}`);
    }
  }
  for (const id of REQUIRED_MANUAL_GATES) {
    if (!seenManual.has(id)) rejections.push(`missing required gate-results manual gate: ${id}`);
  }

  return { ...summary, rejections, pass: rejections.length === 0 };
}

function addFinding(findings, category, severity, message, file = null) {
  findings.push({ category, severity, message, file });
}

function award(checks, findings, category, weight, condition, message, file = null) {
  checks[category] = checks[category] ?? { score: 0, max: 0 };
  checks[category].max += weight;
  if (condition) {
    checks[category].score += weight;
    return;
  }
  addFinding(findings, category, "warn", message, file);
}

function awardRatio(checks, findings, category, weight, passed, total, message) {
  checks[category] = checks[category] ?? { score: 0, max: 0 };
  checks[category].max += weight;
  const ratio = total === 0 ? 1 : passed / total;
  checks[category].score += weight * ratio;
  if (passed < total) {
    addFinding(findings, category, "warn", `${message}: ${passed}/${total}`);
  }
}

function portableFiles() {
  return walk(skillRoot).filter((file) => /\.(md|mjs|json)$/.test(file));
}

function installFiles() {
  return walk(skillRoot);
}

function scanPortableFiles(files) {
  return files.map((file) => ({ file, text: read(file) }));
}

function includesAny(scanned, regex) {
  return scanned.filter(({ text }) => regex.test(text));
}

function loadScenarioFixture(findings) {
  const fixture = path.join(scriptDir, "fixtures/release-scenarios.json");
  if (!existsSync(fixture)) {
    addFinding(findings, "Scenario readiness", "warn", "Missing release scenario fixture", fixture);
    return [];
  }
  try {
    const payload = JSON.parse(readFileSync(fixture, "utf-8"));
    return Array.isArray(payload.profiles) ? payload.profiles : [];
  } catch (error) {
    addFinding(findings, "Scenario readiness", "critical", `Invalid release scenario fixture ${fixture}: ${error.message}`, fixture);
    return [];
  }
}

function classifyProjectRoot(value) {
  const [name, ...rest] = value.split("=");
  const root = rest.join("=");
  const missing = !name || !root || !existsSync(root);

  if (missing) {
    return { name: name || value, root, exists: false, signals: [], recommendedMode: "missing" };
  }

  try {
    return inspectProjectRoot(name, root);
  } catch (error) {
    // e.g. ENOTDIR when the profile root is a file, or permission errors.
    return {
      name,
      root,
      exists: false,
      signals: [],
      recommendedMode: "unreadable",
      error: error.message,
    };
  }
}

function inspectProjectRoot(name, root) {
  const warnings = [];
  const has = (relativePath) => existsSync(path.join(root, relativePath));
  const rootFiles = readdirSync(root);
  const packageJsonPath = path.join(root, "package.json");
  let packageJson = {};
  if (existsSync(packageJsonPath)) {
    try {
      packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
    } catch (error) {
      warnings.push(`Malformed package.json at ${packageJsonPath}: ${error.message}`);
    }
  }
  const profileText = `${name} ${root} ${packageJson.name ?? ""}`.toLowerCase();
  const dependencies = {
    ...packageJson.dependencies,
    ...packageJson.devDependencies,
  };
  const frameworks = [
    has("next.config.js") || has("next.config.mjs") || dependencies.next ? "next" : null,
    has("astro.config.mjs") || has("astro.config.ts") || dependencies.astro ? "astro" : null,
    has("convex") || dependencies.convex ? "convex" : null,
    dependencies["@vercel/analytics"] ? "vercel-analytics" : null,
  ].filter(Boolean);
  const packageManager = has("bun.lock") || has("bun.lockb") ? "bun" : has("pnpm-lock.yaml") ? "pnpm" : has("yarn.lock") ? "yarn" : has("package-lock.json") ? "npm" : "unknown";
  const hasSeoWorkspace = has(".seo");
  const hasProductMarketing = has(".agents/product-marketing.md");
  const hasSeoContext = has(".seo/context.md");
  const hasLegacyContext =
    has(".seo/strategy.md") || has(".seo/audit.md") || has(".agents/product-marketing.md");
  const hasAdapters =
    has(".seo/adapters") &&
    readdirSync(path.join(root, ".seo/adapters")).some((file) => file.endsWith(".md"));
  const localLike = /\b(local|service|legal|gbp|nap|citation|review)\b/.test(profileText);
  const publicSignals = rootFiles.filter((file) =>
    /^(app|pages|src|public|content|posts|blog|astro\.config|next\.config)/.test(file),
  );
  const recommendedMode = hasSeoWorkspace ? "operate" : "bootstrap";
  const recommendedPhases = [
    "classification",
    "technical",
    hasSeoWorkspace ? "measurement" : null,
    publicSignals.length > 0 ? "metadata" : null,
    frameworks.includes("convex") ? "content" : null,
    hasProductMarketing ? "conversion" : null,
    localLike ? "local" : null,
    localLike ? "authority" : null,
  ].filter(Boolean);

  return {
    name,
    root,
    exists: true,
    packageManager,
    frameworks,
    hasSeoWorkspace,
    hasSeoContext,
    hasLegacyContext,
    hasAdapters,
    hasProductMarketing,
    publicSignals,
    recommendedMode,
    recommendedPhases,
    warnings,
  };
}

function compareInstalledSkill(root) {
  const targetSkillRoot = path.join(root, ".agents/skills/seo-growth-workspace");
  if (!existsSync(targetSkillRoot)) {
    return {
      installed: false,
      localOnlyFiles: [],
      modifiedSamePathFiles: [],
      missingFiles: installFiles(),
    };
  }

  const expected = installFiles();
  const expectedSet = new Set(expected);
  const existing = walkRelative(targetSkillRoot);
  const localOnlyFiles = existing.filter((file) => !expectedSet.has(file));
  const modifiedSamePathFiles = expected.filter((file) => {
    const target = path.join(targetSkillRoot, file);
    if (!existsSync(target)) return false;
    return readFileSync(path.join(skillRoot, file), "utf-8") !== readFileSync(target, "utf-8");
  });
  const missingFiles = expected.filter((file) => !existsSync(path.join(targetSkillRoot, file)));

  return {
    installed: true,
    localOnlyFiles,
    modifiedSamePathFiles,
    missingFiles,
  };
}

function profileFindings(profile) {
  if (!profile.exists) {
    return profile.error
      ? [`Profile root could not be inspected (${profile.root}): ${profile.error}`]
      : [`Profile root does not exist: ${profile.root}`];
  }

  const findings = [...(profile.warnings ?? [])];
  if (!profile.hasSeoWorkspace) {
    findings.push("Missing .seo workspace; run bootstrap before operate.");
  } else if (!profile.hasSeoContext) {
    const fallback = profile.hasLegacyContext
      ? "legacy context exists in other .seo/.agents files"
      : "no obvious fallback context files found";
    findings.push(`Missing .seo/context.md (${fallback}).`);
  }

  const contentEngineLike =
    profile.frameworks.includes("convex") ||
    profile.publicSignals.includes("content") ||
    profile.recommendedPhases.includes("content");
  if (contentEngineLike && !profile.hasAdapters) {
    findings.push("Content-engine-like repo has no .seo/adapters/*.md mapping.");
  }

  const installed = compareInstalledSkill(profile.root);
  if (!installed.installed) {
    findings.push("Repo-local .agents/skills/seo-growth-workspace copy is missing.");
  } else {
    if (installed.localOnlyFiles.length > 0) {
      findings.push(`Installed skill has local-only files: ${installed.localOnlyFiles.slice(0, 8).join(", ")}${installed.localOnlyFiles.length > 8 ? ", ..." : ""}.`);
    }
    if (installed.modifiedSamePathFiles.length > 0) {
      findings.push(`Installed skill has modified same-path files: ${installed.modifiedSamePathFiles.slice(0, 8).join(", ")}${installed.modifiedSamePathFiles.length > 8 ? ", ..." : ""}.`);
    }
    if (installed.missingFiles.length > 0) {
      findings.push(`Installed skill is missing files: ${installed.missingFiles.slice(0, 8).join(", ")}${installed.missingFiles.length > 8 ? ", ..." : ""}.`);
    }
  }

  return findings;
}

function evaluate() {
  const findings = [];
  const checks = {};
  const blockingGates = runBlockingGates();
  for (const rejection of blockingGates.rejections) {
    addFinding(findings, "Blocking gates", "critical", rejection);
  }
  for (const gate of blockingGates.gates) {
    if (gate.result !== "PASS") {
      addFinding(
        findings,
        "Blocking gates",
        "critical",
        `blocking gate ${gate.gate} failed (exit ${gate.exit})${gate.failedSections?.length ? `: ${gate.failedSections.join(", ")}` : ""}`,
      );
    }
  }
  const gateResults = consumeGateResults(blockingGates.report);
  for (const rejection of gateResults.rejections) {
    addFinding(findings, "Gate results", "critical", rejection, gateResults.path);
  }
  const skill = read("SKILL.md");
  const references = [
    "references/hub-mode.md",
    "references/migrate-uninstall.md",
    "references/phase-architecture.md",
    "references/operating-loop.md",
    "references/business-context.md",
    "references/admin-preflight.md",
    "references/adapters.md",
    "references/technical-seo.md",
    "references/search-console.md",
    "references/content-ops.md",
    "references/content-engine-webhooks.md",
    "references/pseo-gates.md",
    "references/utility-tool-pages.md",
    "references/ticket-architecture.md",
    "references/internal-linking.md",
    "references/schema-rich-results.md",
    "references/content-refresh.md",
    "references/conversion-cta.md",
    "references/local-seo-gbp.md",
    "references/backlinks-entity.md",
    "references/image-rights.md",
    "references/evidence-conventions.md",
    "references/commercial-integrity.md",
    "references/page-evidence.md",
    "references/page-launch.md",
    "references/community-source-pages.md",
    "references/affiliate-promo-integrity.md",
    "references/ecommerce-seo.md",
    "references/monthly-reporting.md",
    "references/ai-search-visibility.md",
    "references/data-tools.md",
    "references/international-seo.md",
    "references/competitor-profiling.md",
    "references/scheduled-operation.md",
    "references/portfolio-registry.md",
  ];
  const scripts = [
    "scripts/workspace-state.mjs",
    "scripts/seo-doctor.mjs",
    "scripts/bootstrap-seo-workspace.mjs",
    "scripts/gsc-oauth.mjs",
    "scripts/gsc-fetch.mjs",
    "scripts/gsc-opportunities.mjs",
    "scripts/link-graph-analyzer.mjs",
    "scripts/rendered-link-export.mjs",
    "scripts/monthly-report.mjs",
  ];
  const templates = [
    "templates/admin-setup.md",
    "templates/gsc-opportunity.md",
    "templates/content-plan.md",
    "templates/page-evidence.md",
    "templates/local-seo-gbp.md",
    "templates/backlink-gap.md",
    "templates/monthly-report.md",
    "templates/pseo-plan.md",
    "templates/taxonomy.md",
  ];
  // Maintainer tooling lives in dev/seo-growth-workspace, next to this script.
  const releaseToolingFiles = [
    path.join(scriptDir, "release-checklist.md"),
    path.join(scriptDir, "fixtures/release-scenarios.json"),
    path.join(scriptDir, "validate-skill.mjs"),
    path.join(scriptDir, "command-inventory.mjs"),
    path.join(scriptDir, "export-clean-skill.mjs"),
  ];
  const portable = portableFiles();
  const allPortable = scanPortableFiles(portable);
  const combinedPortableText = allPortable.map(({ text }) => text).join("\n").toLowerCase();
  const routedReferences = references.filter((file) => file !== "references/evidence-conventions.md");
  const allReferencesLinked = routedReferences.filter((file) => skill.includes(file)).length;
  const scenarioProfiles = loadScenarioFixture(findings);
  const phaseArchitecture = exists("references/phase-architecture.md")
    ? read("references/phase-architecture.md").toLowerCase()
    : "";
  const releaseChecklistPath = path.join(scriptDir, "release-checklist.md");
  const releaseChecklist = existsSync(releaseChecklistPath)
    ? readFileSync(releaseChecklistPath, "utf-8").toLowerCase()
    : "";

  award(checks, findings, "Structure", 2, /^---[\s\S]*name:\s*seo-growth-workspace[\s\S]*description:/m.test(skill), "SKILL.md frontmatter should include name and description", "SKILL.md");
  awardRatio(checks, findings, "Structure", 7, [...references, ...scripts, ...templates].filter(exists).length, references.length + scripts.length + templates.length, "Required runtime files present");
  awardRatio(checks, findings, "Structure", 3, allReferencesLinked, routedReferences.length, "SKILL.md links current routed references");
  awardRatio(checks, findings, "Structure", 3, releaseToolingFiles.filter((file) => existsSync(file)).length, releaseToolingFiles.length, "Release tooling files present in dev/seo-growth-workspace");

  // Generic contamination patterns: no personal names or private project markers —
  // any user-specific absolute path, email address, or UUID is a packaging leak.
  const contaminationPatterns = [
    { label: "absolute home path", regex: /\/(?:Users|home)\/[A-Za-z0-9._-]+/ },
    {
      label: "email address",
      regex: /[A-Za-z0-9._%+-]+@(?!example\.(?:com|org|net))[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,}/,
    },
    {
      label: "UUID",
      regex: /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i,
    },
  ];
  const contamination = allPortable.flatMap(({ file, text }) => {
    const hits = contaminationPatterns.filter(({ regex }) => regex.test(text));
    return hits.length === 0
      ? []
      : [{ file, markers: hits.map(({ label }) => label).join("/") }];
  });
  const secretExamples = includesAny(allPortable, /(ya29\.|\bsk_(?:live|test)_[A-Za-z0-9]|\bsk-(?:live|test|proj)-[A-Za-z0-9]|GSC_REFRESH_TOKEN=.*[A-Za-z0-9]{12})/);
  award(checks, findings, "Portability", 11, contamination.length === 0, `Portable files contain user-specific contamination: ${contamination.map(({ file, markers }) => `${file} (${markers})`).join(", ")}`);
  award(checks, findings, "Portability", 4, secretExamples.length === 0, `Portable files may contain secret-like examples: ${secretExamples.map(({ file }) => file).join(", ")}`);

  award(checks, findings, "Matt-style architecture", 3, skill.split("\n").length <= 180, "SKILL.md should remain a concise router", "SKILL.md");
  award(checks, findings, "Matt-style architecture", 3, /mode router|choose a mode/i.test(skill), "SKILL.md should explicitly route modes", "SKILL.md");
  award(checks, findings, "Matt-style architecture", 3, /Load only the file needed|Progressive References/i.test(skill), "SKILL.md should enforce progressive disclosure", "SKILL.md");
  award(checks, findings, "Matt-style architecture", 3, /Keep one current focus/i.test(skill), "Skill should keep one current focus", "SKILL.md");
  award(checks, findings, "Matt-style architecture", 3, /Do not print secrets|Never print credential|Do not store or print the token/i.test(combinedPortableText), "Skill should include secret-handling guardrails");
  award(checks, findings, "Matt-style architecture", 3, /phase|ladder|site type|classifier/.test(phaseArchitecture) && skill.includes("references/phase-architecture.md"), "Skill should expose a progressive phase architecture", "references/phase-architecture.md");
  award(checks, findings, "Matt-style architecture", 2, /adapter|content engine|repo-specific/.test(combinedPortableText) && skill.includes("references/adapters.md"), "Skill should preserve repo-local adapter guidance", "references/adapters.md");

  award(checks, findings, "SEO freshness", 3, /robots|sitemap|canonical|noindex|redirect/.test(combinedPortableText), "Skill should cover indexability foundations");
  award(checks, findings, "SEO freshness", 3, /title|description|canonical|open graph|twitter/.test(combinedPortableText), "Skill should cover metadata and snippets");
  award(checks, findings, "SEO freshness", 4, /visible page content|visible-content|visible content/.test(combinedPortableText), "Schema guidance should require visible-content match");
  award(checks, findings, "SEO freshness", 3, /FAQ rich results are no longer appearing|2026-05-07|may 7, 2026/.test(combinedPortableText), "FAQ rich-result deprecation should be explicit");
  award(checks, findings, "SEO freshness", 4, /\b(generative ai|ai search|llms\.txt|AEO|GEO)\b/i.test(combinedPortableText) && /do not|avoid|ignore/.test(combinedPortableText), "AI SEO guidance should reject hacky Google Search gates");
  award(checks, findings, "SEO freshness", 3, /not a full prioritization model|review every row|draft backlog/.test(combinedPortableText), "GSC helper outputs should be framed as draft inputs");

  award(checks, findings, "Marketing usefulness", 3, /CTA|conversion|proof|objection|form/i.test(combinedPortableText), "Skill should cover conversion and CTA work");
  award(checks, findings, "Marketing usefulness", 3, /content|blog|calendar|brief/i.test(combinedPortableText), "Skill should cover content operations");
  award(checks, findings, "Marketing usefulness", 3, /pSEO|programmatic|publish gate/i.test(combinedPortableText), "Skill should cover pSEO gates");
  award(checks, findings, "Marketing usefulness", 2, /GBP|Google Business Profile|NAP|reviews|citations/i.test(combinedPortableText), "Skill should cover local SEO");
  const marketingSkillNames = ["product-marketing", "customer-research", "copywriting", "content-strategy", "programmatic-seo", "ai-seo"];
  const mentionedMarketingSkills = marketingSkillNames.filter((name) => combinedPortableText.includes(name));
  award(checks, findings, "Marketing usefulness", 4, mentionedMarketingSkills.length >= 3, "Skill should bridge to marketing skills when available");

  const expectedScenarioPhases = new Set(scenarioProfiles.flatMap((profile) => profile.expectedPhases ?? []));
  const coveredScenarioPhases = [...expectedScenarioPhases].filter((phase) => phaseArchitecture.includes(phase));
  award(checks, findings, "Scenario readiness", 4, scenarioProfiles.length >= 6, "Release scenarios should include at least six profiles", "fixtures/release-scenarios.json");
  awardRatio(checks, findings, "Scenario readiness", 5, coveredScenarioPhases.length, expectedScenarioPhases.size, "Phase architecture covers expected scenario phases");
  award(checks, findings, "Scenario readiness", 3, /bootstrap|operate|technical-seo-fix|content-ops|pseo-planning|local-seo/.test(phaseArchitecture), "Phase architecture should map scenarios to modes", "references/phase-architecture.md");
  award(checks, findings, "Scenario readiness", 3, /validate-skill|evaluate-release|dry run|bootstrap/.test(releaseChecklist), "Release checklist should define validation and dry-run gates", "references/release-checklist.md");

  const categories = Object.fromEntries(
    Object.entries(checks).map(([category, result]) => [
      category,
      {
        score: Number(result.score.toFixed(2)),
        max: result.max,
      },
    ]),
  );
  const score = Number(Object.values(categories).reduce((sum, item) => sum + item.score, 0).toFixed(2));
  const criticalFindings = findings.filter((finding) => finding.severity === "critical");
  const zeroCategories = Object.entries(categories).filter(([, result]) => result.score === 0).map(([category]) => category);
  const projectProfiles = argValues("--profile-root")
    .filter(Boolean)
    .map((value) => {
      const profile = classifyProjectRoot(value);
      return { ...profile, findings: profileFindings(profile) };
    });

  for (const profile of projectProfiles) {
    for (const finding of profile.findings) {
      addFinding(findings, "Profile readiness", "warn", `${profile.name}: ${finding}`);
    }
  }

  return {
    skill: "seo-growth-workspace",
    score,
    maxScore: 100,
    pass: score >= 85 && criticalFindings.length === 0 && zeroCategories.length === 0 && findings.length === 0 && blockingGates.pass && gateResults.pass,
    passBar: 85,
    gates: {
      minimumScore: score >= 85,
      zeroCriticalFindings: criticalFindings.length === 0,
      noZeroCategory: zeroCategories.length === 0,
      noKnownFindings: findings.length === 0,
      blockingGatesGreen: blockingGates.pass,
      gateResultsGreen: gateResults.pass,
    },
    blockingGates: {
      reportPath: blockingGates.reportPath,
      selfExecuted: blockingGates.selfExecuted,
      rejections: blockingGates.rejections,
      gates: blockingGates.gates,
    },
    gateResults: {
      path: gateResults.path,
      deterministicRows: gateResults.deterministicRows,
      manualRows: gateResults.manualRows,
      manualPass: gateResults.manualPass,
      manualFail: gateResults.manualFail,
      rejections: gateResults.rejections,
      pass: gateResults.pass,
    },
    categories,
    findings,
    scenarioProfiles: scenarioProfiles.map(({ id, siteType, expectedModes, expectedPhases }) => ({
      id,
      siteType,
      expectedModes,
      expectedPhases,
    })),
    projectProfiles,
  };
}

function printMarkdown(result) {
  const gateLines = [
    ...result.blockingGates.rejections.map((reason) => `- report rejected: ${reason}`),
    ...result.blockingGates.gates.map((gate) => `- ${gate.gate}: ${gate.result} (exit ${gate.exit})${gate.failedSections?.length ? ` — ${gate.failedSections.join(", ")}` : ""}`),
  ];
  console.log(`# SEO growth workspace release evaluation

Score: ${result.score}/${result.maxScore}
Pass: ${result.pass ? "yes" : "no"}

## Blocking gates

${gateLines.join("\n")}

## Gate results artifact

- artifact: ${result.gateResults.path}
- deterministic rows: ${result.gateResults.deterministicRows}
- manual rows: ${result.gateResults.manualRows} (PASS ${result.gateResults.manualPass} / FAIL ${result.gateResults.manualFail})
- pass: ${result.gateResults.pass ? "yes" : "no"}
${result.gateResults.rejections.map((reason) => `- rejected: ${reason}`).join("\n")}

## Categories

| Category | Score |
| --- | ---: |
${Object.entries(result.categories)
  .map(([category, value]) => `| ${category} | ${value.score}/${value.max} |`)
  .join("\n")}

## Findings

${result.findings.length === 0 ? "No findings." : result.findings.map((finding) => `- ${finding.severity}: ${finding.category}: ${finding.message}${finding.file ? ` (${finding.file})` : ""}`).join("\n")}
`);
}

if (args.includes("--help") || args.includes("-h")) {
  console.log(usage());
  process.exit(0);
}

const result = evaluate();
if (args.includes("--json")) {
  console.log(JSON.stringify(result, null, 2));
} else {
  printMarkdown(result);
}

process.exit(result.pass ? 0 : 1);
