# align.py: match every lyric word to a sung word time, then write src/song.js (SONG + LYRICS) for the engine.
#   python music/align.py music/take1.analysis.json --audio assets/song.mp3 [--alias Andy=andi]
# Alignment is a difflib match on normalised words, so whisper's mishearings ("what's up" for WhatsApp)
# only cost the words they touch; unmatched words are interpolated between their matched neighbours.
import argparse, json, re, unicodedata, difflib, pathlib
ap = argparse.ArgumentParser(); ap.add_argument('analysis'); ap.add_argument('--audio', required=True)
ap.add_argument('--alias', action='append', default=[], help='Word=heard pairs, e.g. Andy=andi (the sung spelling)')
ap.add_argument('--lyrics', default=str(pathlib.Path(__file__).with_name('lyrics.md'))); ap.add_argument('--out', default='src/song.js')
a = ap.parse_args()
A = json.load(open(a.analysis))
norm = lambda w: re.sub(r'[^a-z0-9ñ]', '', unicodedata.normalize('NFKD', w.lower()).encode('ascii', 'ignore').decode())
alias = {norm(k): norm(v) for k, v in (p.split('=') for p in a.alias)}
lines = [l.strip() for l in open(a.lyrics) if l.strip() and not l.lstrip().startswith(('[', '('))]
lw = [(i, w) for i, l in enumerate(lines) for w in l.split()]
sw = [(w['start'], w['end'], norm(w['word'])) for s in A['segments'] for w in s.get('words', [])]
m = difflib.SequenceMatcher(None, [alias.get(norm(w), norm(w)) for _, w in lw], [x[2] for x in sw], autojunk=False)
t = [None] * len(lw)
for blk in m.get_matching_blocks():
    for k in range(blk.size): t[blk.a + k] = sw[blk.b + k][0]
known = [k for k, v in enumerate(t) if v is not None]
for k in range(len(t)):                                   # interpolate the gaps
    if t[k] is None:
        lo = max([j for j in known if j < k], default=None); hi = min([j for j in known if j > k], default=None)
        t[k] = t[lo] + .3 * (k - lo) if hi is None else (t[hi] - .3 * (hi - k) if lo is None else t[lo] + (t[hi] - t[lo]) * (k - lo) / (hi - lo))
ends = {s[0]: s[1] for s in sw}
out = []
for i, L in enumerate(lines):
    ws = [round(t[k], 2) for k, (j, _) in enumerate(lw) if j == i]
    last = next(k for k in range(len(lw) - 1, -1, -1) if lw[k][0] == i)
    out.append({'text': L, 'start': ws[0], 'end': round(ends.get(t[last], t[last] + .5), 2), 'words': ws})
    print('%6.2f-%6.2f %s' % (out[-1]['start'], out[-1]['end'], L))
print('matched %d of %d lyric words' % (len(known), len(lw)))
song = {'file': a.audio, 'dur': round(A['duration'], 2), 'bpm': round(A['tempo'], 2), 'beats': [round(b, 3) for b in A['beats']]}
pathlib.Path(a.out).write_text('// Generated by music/align.py: beat grid + word timings of the chosen take. Re-run after changing takes.\n'
    f'const SONG = {json.dumps(song)};\nconst LYRICS = {json.dumps(out, ensure_ascii=False)};\n')
